# =========================
# DATABASE
# ========================= 
spring.datasource.url=jdbc:postgresql://ep-morning-mouse-b1ihoepr.c-5.eu-central-1.aws.neon.tech:5432/DBPostgresRAG
spring.datasource.username=DBPostgresRAG_owner
spring.datasource.password=npg_qy5i3dYpbItD

# =========================
# SERVER
# =========================
server.port=${PORT:10000}
#server.port=${PORT}
# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# LOGGING
# =========================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.web=DEBUG


# =========================
# HIKARI POOL (IMPORTANTE)
# ========================
# è importante perché il database su Render è limitato: se apri troppe connessioni insieme, 
# si blocca tutto e ottieni gli errori che hai visto prima.

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
